from __future__ import annotations
from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from bf2.core import ast as A

class ASTVisitor:
    """Base class for all AST visitors (Emitter, Interpreter, TypeChecker)."""
    
    def visit(self, node: Any) -> Any:
        return node.accept(self)

    # Top-level items
    def visit_module(self, node: A.Module) -> Any: ...
    def visit_struct_decl(self, node: A.StructDecl) -> Any: ...
    def visit_segment_decl(self, node: A.SegmentDecl) -> Any: ...
    def visit_function_def(self, node: A.FunctionDef) -> Any: ...
    def visit_reactor_def(self, node: A.ReactorDef) -> Any: ...
    def visit_block(self, node: A.Block) -> Any: ...

    # Expressions
    def visit_ref_expr(self, node: A.RefExpr) -> Any: ...
    def visit_ident(self, node: A.Ident) -> Any: ...
    def visit_int_lit(self, node: A.IntLit) -> Any: ...
    def visit_float_lit(self, node: A.FloatLit) -> Any: ...
    def visit_bool_lit(self, node: A.BoolLit) -> Any: ...
    def visit_string_lit(self, node: A.StringLit) -> Any: ...
    def visit_unary(self, node: A.Unary) -> Any: ...
    def visit_bin_op(self, node: A.BinOp) -> Any: ...
    def visit_call(self, node: A.Call) -> Any: ...

    # Statements
    def visit_move_op(self, node: A.MoveOp) -> Any: ...
    def visit_move_rel(self, node: A.MoveRel) -> Any: ...
    def visit_cell_arith(self, node: A.CellArith) -> Any: ...
    def visit_cell_arith_ref(self, node: A.CellArithRef) -> Any: ...
    def visit_cell_assign_lit(self, node: A.CellAssignLit) -> Any: ...
    def visit_load_op(self, node: A.LoadOp) -> Any: ...
    def visit_store_op(self, node: A.StoreOp) -> Any: ...
    def visit_swap_op(self, node: A.SwapOp) -> Any: ...
    def visit_assign_stmt(self, node: A.AssignStmt) -> Any: ...
    def visit_var_decl(self, node: A.VarDecl) -> Any: ...
    def visit_ptr_decl(self, node: A.PtrDecl) -> Any: ...
    def visit_ptr_arith(self, node: A.PtrArith) -> Any: ...
    def visit_ptr_write(self, node: A.PtrWrite) -> Any: ...
    def visit_ptr_read(self, node: A.PtrRead) -> Any: ...
    def visit_if_stmt(self, node: A.IfStmt) -> Any: ...
    def visit_loop_bf(self, node: A.LoopBF) -> Any: ...
    def visit_loop_counted(self, node: A.LoopCounted) -> Any: ...
    def visit_label_stmt(self, node: A.LabelStmt) -> Any: ...
    def visit_jump_stmt(self, node: A.JumpStmt) -> Any: ...
    def visit_io_stmt(self, node: A.IOStmt) -> Any: ...
    def visit_call_stmt(self, node: A.CallStmt) -> Any: ...
    def visit_ret_stmt(self, node: A.RetStmt) -> Any: ...
    def visit_alloc_stmt(self, node: A.AllocStmt) -> Any: ...
    def visit_free_stmt(self, node: A.FreeStmt) -> Any: ...
    def visit_expr_stmt(self, node: A.ExprStmt) -> Any: ...
    def visit_segment_stmt(self, node: A.SegmentStmt) -> Any: ...
    def visit_struct_stmt(self, node: A.StructStmt) -> Any: ...
    def visit_unlink_stmt(self, node: A.UnlinkStmt) -> Any: ...
